# YAML (YAML Ain't Markup Language) ,commonly used for configuration files, data exchange, and debugging.
# Configuration settings can include things like:
# File paths and directories
# Database connections
# API keys and credentials
# Logging settings
# Environment variables

artifacts_root: artifacts
#root directory where all artifacts (output files) will be stored.

data_ingestion:
  root_dir: artifacts/data_ingestion
  # Root directory for storing artifacts related to data ingestion.

  source_URL: https://drive.google.com/file/d/126RxZz9GlPf4NhZEaxsZbNwTdMbchYJz/view?usp=drive_link
  #URL of the source data file (in this case, a Google Drive link).

  local_data_file: artifacts/data_ingestion/data.zip
  #Local file path where the data will be downloaded and stored (in ZIP format).

  unzip_dir: artifacts/data_ingestion
  #Directory where the ZIP file will be unzipped and the raw data will be stored.


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  #Root directory for storing artifacts related to preparing the base model.
  
  base_model_path: artifacts/prepare_base_model/base_model.h5
  #Path to the initial base model file (HDF5 format).
  
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
  #Path to the updated base model file (HDF5 format) after modification or fine-tuning.