# YAML (YAML Ain't Markup Language) ,commonly used for configuration files, data exchange, and debugging.
# Configuration settings can include things like:
# File paths and directories
# Database connections
# API keys and credentials
# Logging settings
# Environment variables

artifacts_root: artifacts
#root directory where all artifacts (output files) will be stored.

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/126RxZz9GlPf4NhZEaxsZbNwTdMbchYJz/view?usp=drive_link
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion